prefix graph: <https://data.vlaanderen.be/id/graph/>

SELECT DISTINCT ?uri
WHERE
{
    { ?s ?p ?uri .
    FILTER regex(str(?uri), "https://data.vlaanderen.be/ns/omgevingsvergunning#", "i") }
    UNION
    { ?s ?uri ?o .
    FILTER regex(str(?uri), "https://data.vlaanderen.be/ns/omgevingsvergunning#", "i") }
    UNION
    { ?uri ?p ?o.
    FILTER regex(str(?uri), "https://data.vlaanderen.be/ns/omgevingsvergunning#", "i") }
}

ORDER BY ?uri
